version: '3'
services:
    mysql:
        image: mysql:8.0.32
        container_name: mysql
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root123
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/query:/docker-entrypoint-initdb.d
